use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.002005
eval "use Test::Spelling 0.12; use Pod::Wordlist::hanekomu; 1" or die $@;


add_stopwords(<DATA>);
all_pod_files_spelling_ok('bin', 'lib');
__DATA__
XKCD
cryptographically
freevocabulary
fs
ga
passphrase
rrrr
wordfrequency
wordlist
wordlists
David
Golden
lib
Crypt
Diceware
Wordlist
Beale
Original
Common
